// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfbyfyjqusmtlwqqbsak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYnlmeWpxdXNtdGx3cXFic2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NTQxMTEsImV4cCI6MjA4ODUzMDExMX0.TmkgvMSNe88Gt_o5zyx8-AyzHwUs7fmRAbh6eCXQ-A8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});